name: demo

on:
    push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
          - name: Setup Node js
            uses: actions/setup-node@v6
            with:
              node-version: '15'    